name: CI
on:
  push: { branches: [main] }
  pull_request: { types: [opened, synchronize, reopened, ready_for_review], branches: [main] }
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  check:  { uses: dioxuslabs/dioxus-ci/.github/workflows/check.yml@main }
  test:   { uses: dioxuslabs/dioxus-ci/.github/workflows/test.yml@main }
  clippy: { uses: dioxuslabs/dioxus-ci/.github/workflows/clippy.yml@main }
  fmt:    { uses: dioxuslabs/dioxus-ci/.github/workflows/fmt.yml@main }
